### PR TITLE
Add test-idp-ssl role

### PR DESCRIPTION
**Pull request by mrvanes**

### CODE REVIEW

**Comment by baszoetekouw** [comment]
@mrvanes I've renamed this role to something that is less confusing (hopefully), and cleaned up the config a bit.

It now basically works, except that not all attributes are gathered from the x509 cert correctly.  The new IdP gives:

Screenshot 2023-09-19 at 13 45 54

While the old one gives:
Screenshot 2023-09-19 at 13 56 56

So please fix:
- [ ] uid
- [ ] subject-id (NB: is also broken in the old IdP, should be `sha256(<uid>)@<sho>`
- [ ] mail
- [ ] eppn

**Review by baszoetekouw — CHANGES_REQUESTED** [review]
See comment above.

**Comment by mrvanes** [comment]
Subject-id is fixed
https://github.com/SURFscz/remoteuserssl/commit/c50150795a0d6bed246167c0452d2cad03018d9e

Can't reproduce uid/mail/eppn problem. My DN correctly contains emailAddress (case-sensitive):
`emailAddress=martin.vanes@surf.nl,CN=Martin van Es,C=NL,ST=Utrecht,street=Moreelsepark 48,O=SURF B.V.,postalCode=3511 EP`
https://github.com/SURFscz/remoteuserssl/blob/main/src/Auth/Source/RemoteUserSSL.php#L81
image

**Comment by mrvanes** [comment]
https://github.com/SURFscz/remoteuserssl/commit/ec3cf66d00e5d8a617e8837fb64523301c18fbe0

**Review by baszoetekouw — APPROVED** [review]

**Pull request merged**
